# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np
arr = np.arange(2 , 50 , 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [38]:
### Accept first list from user
list1 = []
i=5
print("Enter  elements for list1")
while i>=1:
        n=int(input())
        i=i-1
        list1.append(n)
print("\n",list1) 

print(type(list1))
# Accept 2 list from user

list2 = []
i=5
print("Enter elements for list2")
while i>=1:
        n=int(input())
        i=i-1
        list2.append(n)
print("\n",list2) 


print(type(list2))

# Conver list into Array
print("\n Converting List into Array")
Arr1 = (np.array(list1))
Arr2 = (np.array(list2))

print("\n Array 1     ",Arr1)  
print(type(Arr1))

print("\n Array 2     ",Arr2)
print(type(Arr2))

print("\n Concatenetion of Two Array")
Arr3 = np.concatenate((Arr1,Arr2))  #  Concatenete Array
print(Arr3)

print("\n Sorting of Array ")
print(np.sort(Arr3))         # Sorting of specific Array



Enter  elements for list1
1
2
3
6
7

 [1, 2, 3, 6, 7]
<class 'list'>
Enter elements for list2
5
6
7
8
4

 [5, 6, 7, 8, 4]
<class 'list'>

 Converting List into Array

 Array 1      [1 2 3 6 7]
<class 'numpy.ndarray'>

 Array 2      [5 6 7 8 4]
<class 'numpy.ndarray'>

 Concatenetion of Two Array
[1 2 3 6 7 5 6 7 8 4]

 Sorting of Array 
[1 2 3 4 5 6 6 7 7 8]


# Question 3

In [3]:
Arr1 = np.array([[1,2,3],[4,5,6]])
Arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Dimension of ndarray
print("No. of Dimension: " , Arr1.ndim)

No. of Dimension:  2


In [5]:
# Size of Array
print("Size of Array", Arr1.size)

Size of Array 6


# Question 4

In [9]:
arr_1d = np.array([1,2,3,4]) # 1D Array
print(arr_1d)
print("Dimension",arr_1d.ndim)

[1 2 3 4]
Dimension 1


In [10]:
# Coverting 1D Array into 2D Array
convert_to_2d = np.reshape(arr_1d,(2,2))
print(convert_to_2d)
print("Dimension",convert_to_2d.ndim)

[[1 2]
 [3 4]]
Dimension 2


# Question 5

In [28]:
A = np.array([[1,2,3],[4,5,6],[6,7,8]])
B = np.array([1,2,3,3])
print("\n Array A")
print("\n",A)

print("\n Array B     ",B)


 Array A

 [[1 2 3]
 [4 5 6]
 [6 7 8]]

 Array B      [1 2 3 3]


In [29]:
np.vstack((A))  # Stack  A Vertically

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [30]:

np.hstack((A)) # stack A Horizontally

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [31]:
np.vstack((B))  # Stack B Vertically


array([[1],
       [2],
       [3],
       [3]])

In [32]:
np.hstack((B))  # Stack B horizontally

array([1, 2, 3, 3])

# Question 6

In [36]:
print("Given Array Are")
list1 = [1,2,3,4,4,4,4,3,3,2,7,8,6,5,3]
list2 = (np.array(list1))
print("\n",list2)
l1 = []
count = 0
for item in list2:
    if item not in l1:
        count += 1
        l1.append(item)
        
print("\nNumber  Of Unique Item :", count)
print("\nUnique Numbers Are   ",l1)
        

Given Array Are

 [1 2 3 4 4 4 4 3 3 2 7 8 6 5 3]

Number  Of Unique Item : 8

Unique Numbers Are    [1, 2, 3, 4, 7, 8, 6, 5]
